name = "MyFirstPackage"
uuid = "ebe20685-ac58-45ff-a81b-7ca0ad59c05f"
authors = ["xuezhencai"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
